baseURL = 'https://billg-splunk.github.io/'
languageCode = 'en-us'
title = "Bill Grant's Observability Blog"
#theme = "ananke"
#theme = "hugo_theme_pickles"
theme = "mainroad"
publishDir = './'

[params]
  paginate = 10